### ISSUE TITLE
mainWidget - Add responsive Design, style adjustments, ...

### ISSUE THREAD

**Issue by NRquadrat** [hmerk/main_widget#28]
**Is your feature request related to a problem? Please describe.**
- The mainWidget is not designed for responsive design.
- oh-repeaters can be reduced to possibly improve performance.
- Several areas do not comply with the DesignSpecs.

**Describe the solution you'd like**
- Integration of f7-swiper instead of oh-repeaters.
- Diverese style adjustments.
- Create basis for responsive design.
- Icon adjustment of the bottomNavbar to use Iconify. Use different sources is not advised. (svg-container). Preparation to eventually introduce an svg icon set as a local source.
- Definition of css classes for efficient styling.

**Describe alternatives you've considered**
...
**Additional context**

![Test - Imgur](https://user-images.githubusercontent.com/79790877/216075851-26f8d730-000e-491e-8520-d3460e5a2e97.gif)

**Comment by hmerk** [comment]
Thanks for sharing this informations, I really love what I can see.
Happy to review your code once you have created the MR's.

**Comment by NRquadrat** [comment]
But a note:
The change to the mainWidget only creates the basis for a responsive design.
The actual breakpoints are contained in the widget_Floors&Rooms.

The image shown is only accessible with a few PRs.

Apart from the preparation for a responsive design, the above-mentioned improvements are then added.

**Comment by hmerk** [comment]
If it needs several PRs, thats fine.
I will review all before merging to be shure to have a fully working set of widgets.
