### ISSUE TITLE
Correct display of Things

### ISSUE THREAD

**Issue by NRquadrat** [hmerk/main_widget#30]
**Describe the bug**
The display of things in widget_Floors&Rooms is not correct in my opinion.
When I click on Floors all lights of the Smarthome appear.
When I click on Rooms all the lights of the Smarthome appear.
When I click on Floors
-> Floors -> all lights of the Smarthome
-> Floors -> Shades -> all shutters of the Smarthome
-> Floors -> Climate -> all heaters of the Smarthome
The same when I click on Rooms.
The same when I click on Floors -> LivingRoom

**To Reproduce**
see above

**Expected behavior**

In my opinion:

-> Floors -> all things of Smarthome
-> Floors -> Lights -> only Lights of the Smarthome
-> Floors -> Livingroom -> all things of LivingRoom
-> Floors -> Livingroom -> Lights -> only the Lights of LivingRoom

To be accurate, initially should always be displayed all Things.

For discussion ;-)

**Comment by hmerk** [comment]
What you want is what we had some time ago, but having a bigger installation, initial loading took really long before anything was shown. Therefore I limited to show only lights if no foor or room is selected. Selecting one of the other thing types would then show those widgets/cards.

**Comment by NRquadrat** [comment]
I think it would be better to initially run all repeaters so that a better performace can be achieved during switching.
We can test this again with my Floors&Rooms structure as soon as I am ready.

Just as a suggestion.

**Comment by hmerk** [comment]
I am happy to test it 😉
