### ISSUE TITLE
mainWidget - The filter function of oh-repeater for all Rooms is wrong

### ISSUE THREAD

**Issue by NRquadrat** [hmerk/main_widget#34]
**Describe the bug**
The Filter function is wrong:

`filter: (loop.roomArray.metadata) && ((loop.roomArray.metadata.semantics.value).includes("Room")  || (loop.roomArray.metadata.semantics.value).includes("Corridor")) && (loop.roomArray.metadata.semantics.config.hasLocation == vars.objVar.floor)`

should be

`filter: (loop.roomArray.metadata) && ((loop.roomArray.metadata.semantics.value).includes("Room")  || (loop.roomArray.metadata.semantics.value).includes("Corridor"))`

because the objVar.floor isn't set in this moment. 
It is not noticeable because invisibility is set.
`visible: '=!vars.objVar ? false : (vars.objVar.selectSection=="SECTION2" && !vars.objVar.floor) ? true : false'`

The aim is to display all rooms.

**Comment by hmerk** [comment]
Are you shure you are looking at the correct repeater ?
There is one showing all rooms when no floor is selected and another one showing just the rooms in a particular floor.
The oh-repeater might not show anything if floor is not selected, but we need to hide the empty row or the row with all rooms if a floor is selected, therefore the visibility tag.

**Comment by NRquadrat** [comment]
First repeater for all Rooms:

>                 - component: f7-row
>                   config:
>                     style:
>                       width: 100%
>                       height: auto
>                     visible: '=!vars.objVar ? false : (vars.objVar.selectSection=="SECTION2" && !vars.objVar.floor) ? true : false'

Visible when:
Section 2 (Rooms) and objVar.floors NOT true
So display of all rooms.

The Filterfuction of the included oh-repeater:

>                             - component: oh-repeater
>                               config:
>                                 fetchMetadata: metadata,semantics,widgetOrder
>                                 filter: (loop.roomArray.metadata) && ((loop.roomArray.metadata.semantics.value).includes("Room")  || (loop.roomArray.metadata.semantics.value).includes("Corridor")) && (loop.roomArray.metadata.semantics.config.hasLocation == vars.objVar.floor)
>                                 for: roomArray
>                                 fragment: true
>                                 itemTags: ","
>                                 sourceType: itemsWithTags

Filter:
loop.roomArray.metadata = true
**AND**
loop.roomArray.metadata.semantics.value).includes("Room") **OR** (loop.roomArray.metadata.semantics.value).includes("Corridor")
**AND**
loop.roomArray.metadata.semantics.config.hasLocation == vars.objVar.floor

In my opinion, all rooms should be displayed here. The objVar.floor is not set at this moment.

Of course, this is not noticeable because objVar.floors NOT true makes it invisible.
I hope I have been able to explain it clearly.
Or am I making a mistake in my thinking?  :-D

**Comment by hmerk** [comment]
Hmm, wondering wha it worked before,, but I know understand what you wrote.
I think, the two visible filters got somehow swaped.

**Rooms in selected floor**
```
                    visible: '=!vars.objVar ? false : (vars.objVar.selectSection=="SECTION2" && vars.objVar.floor) ? true : false'

                                filter: (loop.roomArray.metadata) 
								&& ((loop.roomArray.metadata.semantics.value).includes("Room")  
								|| (loop.roomArray.metadata.semantics.value).includes("Corridor")) 
								&& (loop.roomArray.metadata.semantics.config.hasLocation == vars.objVar.floor)
```
**Rooms without floor selection**
```
                    visible: '=!vars.objVar ? false : (vars.objVar.selectSection=="SECTION2" && !vars.objVar.floor) ? true : false'

                                filter: (loop.roomArray.metadata) 
								&& ( (loop.roomArray.metadata.semantics.value).includes("Room") 
								|| (loop.roomArray.metadata.semantics.value).includes("Corridor") )
```

**Comment by NRquadrat** [comment]
Your Filter in ,,Rooms without floor selection'' is like my suggestion in first post. 👍 
So we agree and I can fix it with the next PR? ;-)

**Comment by hmerk** [comment]
Yes !!! Just wondering, why it worked so far....

**Comment by NRquadrat** [comment]
loop.roomArray.metadata.semantics.config.hasLocation == vars.objVar.floor 
in this moment -> true becaus the objVar.floor is empty
I think so..
But it doesn't really matter. In any case, it is wrong :-D
