### ISSUE TITLE
mainWidget - Improvement for display speed

### ISSUE THREAD

**Issue by NRquadrat** [hmerk/main_widget#35]
**Is your feature request related to a problem? Please describe.**
The visibility of the oh-repeater content is too slow.

**Describe the solution you'd like**
The slow speed comes from the visible parameter in the rows.
I suggest using cdd atrribute display: none & display: "".
The containers are created initially and only made invisible.
First tests show a performance improvement.

Actual:

>                 - component: f7-row
>                   config:
>                     style:
>                       width: 100%
>                     visible: '=vars.objVar ? (vars.objVar.selectSection=="SECTION1") ? true : false : false'

Suggestion:
>                 - component: f7-row
>                   config:
>                     class:
>                       - align-items-center
>                       - display-flex
>                     style:
>                       width: 100%
>                       height: auto
>                       display: '=vars.objVar ? (vars.objVar.selectSection=="SECTION1") ? "" : "none !important" : "none !important"'

**Comment by hmerk** [comment]
Never seen this, but seems to be a good suggestion.
