### ISSUE TITLE
mainWidget - f7-swiper navigation buttons outside container

### ISSUE THREAD

**Issue by NRquadrat** [hmerk/main_widget#36]
**Is your feature request related to a problem? Please describe.**
Currently, the navigation buttons are located inside the container. This is unattractive because the chevrons overlap the buttons for rooms.
Pressing the swiper buttons correctly is not always possible.

**Describe the solution you'd like**
Move f7-swiper buttons from the container to the outside.
Better operability due to larger button area.

**Additional context**
![grafik](https://user-images.githubusercontent.com/79790877/217859539-45a29e70-082b-4410-8810-b8386bcb65cf.png)

**Comment by hmerk** [comment]
👍👍
