### ISSUE TITLE
homeCard - wrong Margin in first block

### ISSUE THREAD

**Issue by NRquadrat** [hmerk/main_widget#38]
**Describe the bug**
The first blog has a margin -1em.
This means that, for example, the WeatherCard is not displayed correctly.

**To Reproduce**
This is what it looks like.
![grafik](https://user-images.githubusercontent.com/79790877/218277682-22cebe9f-e2dd-489d-946e-a664decc968d.png)

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/79790877/218277725-d664de06-55f1-47e2-af3b-73c55dacd724.png)

**Screenshots**
shown up

**Fix suggestion**
The first step is to remove the margin.
The second step is to examine the general layout in order to design it responsively.

**Comment by hmerk** [comment]
Good catch ! feel free to remove the margin and then lets discuss what you think is needed.
In general, I do not want to provide the weather widget within the project but would prefer to just refer to the official version.
